
#ifndef	__CPU_MEM_MAP__
#define __CPU_MEM_MAP__
#include "stm32f4xx_hal.h"


#define FLASH_USER_APP_START_ADDRESS     (uint32_t)0x08002800
#define FLASH_USER_DATA_START_ADDRESS    (uint32_t)0x08030000

#define FLASH_ADDR_DEV_1_PARA				(FLASH_USER_DATA_START_ADDRESS + FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_2_PARA				(FLASH_USER_DATA_START_ADDRESS + 2*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_3_PARA				(FLASH_USER_DATA_START_ADDRESS + 3*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_4_PARA				(FLASH_USER_DATA_START_ADDRESS + 4*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_5_PARA				(FLASH_USER_DATA_START_ADDRESS + 5*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_6_PARA				(FLASH_USER_DATA_START_ADDRESS + 6*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_7_PARA				(FLASH_USER_DATA_START_ADDRESS + 7*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_8_PARA				(FLASH_USER_DATA_START_ADDRESS + 8*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_9_PARA				(FLASH_USER_DATA_START_ADDRESS + 9*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_10_PARA				(FLASH_USER_DATA_START_ADDRESS + 10*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_11_PARA				(FLASH_USER_DATA_START_ADDRESS + 11*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_12_PARA				(FLASH_USER_DATA_START_ADDRESS + 12*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_13_PARA				(FLASH_USER_DATA_START_ADDRESS + 13*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_14_PARA				(FLASH_USER_DATA_START_ADDRESS + 14*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_15_PARA				(FLASH_USER_DATA_START_ADDRESS + 15*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_16_PARA				(FLASH_USER_DATA_START_ADDRESS + 16*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_17_PARA				(FLASH_USER_DATA_START_ADDRESS + 17*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_18_PARA				(FLASH_USER_DATA_START_ADDRESS + 18*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_19_PARA				(FLASH_USER_DATA_START_ADDRESS + 19*FLASH_PAGE_SIZE)
#define FLASH_ADDR_DEV_20_PARA				(FLASH_USER_DATA_START_ADDRESS + 20*FLASH_PAGE_SIZE)
/*
0x0800 0000 -  0x0802 FFFF   APP  192k
0x0803 0000 -  0x0803 07FF   MODBUS DATA 2K 
0x0803 0800 -  0x0803 A7FF   DEVICE DATA 40K 
0x0803 A800 -  0x0803 AFFF   ENCRYPT DATA 2K 
0x0803 B000 -  0x0803 FFFF   BOOT DATA 20K 



*/


#endif
